'''
Usage:
    dragonboard_calc_calib_constants <inputfile> <outputfile> [options]

Options:
    -n <n>, --n-jobs=<n>     How many threads to use [default: 1]
    -v <v>, --verbosity=<v>  Verbosity of joblib [default: 5]

fit raw data with powerlaw a*x**b+c and calculate chisquare for every fit.
data is contained in a pandas data frame.
inputfile: .h5 file generated by dragonboard_dataextraction without using a calibration
'''

import pandas as pd
from astropy.io import fits
from scipy.optimize import curve_fit
from joblib import Parallel, delayed
import numpy as np
import logging
import os
import sys
from docopt import docopt

logging.basicConfig(level=logging.INFO)


def f(x, a, b, c):
    return a * x ** b + c


def fit(df, cell, plot=False):
    big_time = df.delta_t.quantile(0.75)
    p0 = [
        9e-2,
        -0.66,
        df.adc_counts[df.delta_t >= big_time].mean(),
    ]
    try:
        (a, b, c), cov = curve_fit(
            f,
            df['delta_t'],
            df['adc_counts'],
            p0=p0,
            maxfev=100000,
        )
    except RuntimeError:
        logging.error('Could not fit cell {}'.format(cell))
        return np.full(4, np.nan)

    ndf = len(df.index) - 3
    residuals = df['adc_counts'] - f(df['delta_t'], a, b, c)
    chisquare = np.sum(residuals**2) / ndf

    return a, b, c, chisquare


def main():
    args = docopt(__doc__)

    pool = Parallel(int(args['--n-jobs']), verbose=int(args['--verbosity']))
    ids = np.arange(1024)

    if os.path.isfile(args['<outputfile>']):
        answer = input('Outputfile exists, overwrite? (y / [n]): ')
        if not answer.lower().startswith('y'):
            sys.exit()

    with pd.HDFStore(args['<outputfile>'], 'w') as store:
        f = fits.open(args['<inputfile>'])
        num_events = f[1].data.shape[0]
        print(num_events)
        for pixel in range(1440):
            logging.info('%s', pixel)

            data = pd.DataFrame()
            for key in ('cellIDs', 'deltaT', 'Data'):
                data[key] = (
                    f[1].data[key][:, pixel * 300: (pixel + 1) * 300]
                    .ravel()
                    .byteswap()
                    .newbyteorder()
                )

            data['sample'] = np.tile(np.arange(300), num_events)
            data.rename(columns={'cellIDs': 'cell', 'Data': 'adc_counts', 'deltaT': 'delta_t'}, inplace=True)
            data.dropna(inplace=True)

            data = data[(data['sample'] > 10) & (data['sample'] < 280)]

            by_cell = data.groupby('cell')
            result = pd.DataFrame(
                pool(delayed(fit)(df, name) for name, df in by_cell),
                columns=['a', 'b', 'c', 'chisq_ndf']
            )
            result['pixel'] = pixel
            result['cell'] = ids

            store.append('data', result)


if __name__ == '__main__':
    main()
